version: '3'

services:
    app:
        build: .
        restart: always
        ports:
            - "5000:5000"
        command: npm start
        volumes:
            - .:/usr/app
            - ${VOL_FOLDER}:/usr/app/external
